FROM node:lts-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

COPY . .

ARG FLAG=flag{test_flag}
ENV FLAG=${FLAG}

EXPOSE 3000
CMD ["pnpm", "start"]